apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blockchain-app.name" . }}
  labels:
    {{- include "blockchain-app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "blockchain-app.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "blockchain-app.name" . }}
    spec:
      containers:
        - name: {{ include "blockchain-app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: http
              containerPort: 8080
