apiVersion: v1
kind: Service
metadata:
  name: {{ include "blockchain-app.name" . }}
  labels:
    {{- include "blockchain-app.labels" . | nindent 4 }}
spec:
  ports:
    - port: 8080
      targetPort: http
  selector:
    app.kubernetes.io/name: {{ include "blockchain-app.name" . }}
