name: CI/CD Pipeline

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      env:
        IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/blockchain-app:latest
      run: |
        # Convert IMAGE_NAME to lowercase
        IMAGE_NAME_LOWER=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
        echo "Lowercase image name: $IMAGE_NAME_LOWER"

        # Build and push the Docker image
        docker buildx build --push --tag "$IMAGE_NAME_LOWER" .

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.20.0'

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.5.0'

    - name: Deploy to Kubernetes
      run: |
        # Convert IMAGE_NAME to lowercase
        IMAGE_NAME_LOWER=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')

        helm upgrade --install blockchain-app ./blockchain-app \
          --set image.repository="$IMAGE_NAME_LOWER" \
          --set image.tag=latest
