name: CI/CD Pipeline

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20

    - name: Run unit tests
      run: go test ./...

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/blockchain-app:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.20.0'

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: 'v3.5.0'

    - name: Deploy to Kubernetes
      run: |
        helm upgrade --install blockchain-app ./blockchain-app \
          --set image.repository=ghcr.io/${{ github.repository_owner }}/blockchain-app \
          --set image.tag=latest
