name: CI/CD Pipeline

on:
  push:
    branches:
      - main


jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3


      - name: Run unit tests
        run: go test ./...

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Build and push Docker image
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/k8s:latest
        run: |
          # Convert IMAGE_NAME to lowercase
          IMAGE_NAME_LOWER=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')
          echo "Lowercase image name: $IMAGE_NAME_LOWER"

          # Build and push the Docker image
          docker buildx build --push --tag "$IMAGE_NAME_LOWER" .

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: 'v3.5.0'

      - name: Deploy to Kubernetes
        run: |
          # Convert IMAGE_NAME to lowercase
          IMAGE_NAME_LOWER=$(echo "$IMAGE_NAME" | tr '[:upper:]' '[:lower:]')

          helm upgrade --install blockchain-app ./blockchain-app \
            --set image.repository="$IMAGE_NAME_LOWER" \
            --set image.tag=latest
